### ISSUE TITLE
app_links_platform_interface: 1.0.1 - method_channel_applinks.dart throws no such method

### ISSUE THREAD

**Issue by m-skolnick** [llfbandit/app_links#18]
Device: Android

The following code causes an exception to be thrown
```
    final _applinks = AppLinks();

    final _initialRoute = await _applinks.getInitialAppLink();
```

method_channel_applinks.dart throws no such method at
```
 @override
  Future<String?> getInitialAppLinkString() async {
    final link = await _method.invokeMethod(_getInitialAppLinkMethod);
    return link.isNotEmpty ? link : null;
  }
```

**Comment by llfbandit** [comment]
Did you try to clean your project?
I guess I pushed my pubspec.yaml with relative path.
Don't know if this will help...

**Comment by m-skolnick** [comment]
Yes. Flutter clean does not solve it. 

I did a little deeper debugging. Here's what I found:

![Screen Shot 2022-04-28 at 1 20 42 PM](https://user-images.githubusercontent.com/24857258/165811158-22885e94-d252-4962-803b-7eb259aa4961.png)

I'm not sure why the `getInitialAppLink` method cannot be found though.

**Comment by m-skolnick** [comment]
Thank you! No rush. We'll just pin to `app_links_platform_interface: 1.0.0` for now :) 

Have a wonderful day!

**Comment by llfbandit** [comment]
`app_links_platform_interface "1.0.2"` has been released to fix this `null` pointer.
